# Fallout: New Vegas bridge compatibility

exposeRemixApi = False
presentSemaphoreEnabled = False
client.hookMessagePump = True

clientCmdQueueSize = 10000
clientDataQueueSize = 10000
serverCmdQueueSize = 10000
serverDataQueueSize = 10000
sendCreateFunctionServerResponses = False
