; Fallout: New Vegas vanilla-raster DLAA wrapper

[Remix]
Enabled=1
DLLName=d3d9_remix.dll

[RasterDLSS]
Enabled=1

[Chain]
Preload=
Postload=

[FFP]
Enabled=0

[Skinning]
Enabled=0

[CullingPatch]
Enabled=0

[Lights]
Enabled=0

[Diagnostics]
Enabled=0

[SunCycle]
Enabled=0

[MoonCycle]
Enabled=0
