[ADDON]
AddonPath=.
DisabledAddons=

# Add only after obtaining a compatible add-on from an authorized source.
LoadFromDllMain=renodx-dlss5.addon64

[GENERAL]
EffectSearchPaths=.\
IntermediateCachePath=.\ReShadeCache
NoDebugInfo=1
NoEffectCache=0
PerformanceMode=0
PreprocessorDefinitions=
PresetPath=
PresetShortcutKeys=
SkipLoadingDisabledEffects=0
StartupPresetPath=
TextureSearchPaths=.\

[INPUT]
ForceShortcutModifiers=1
GamepadNavigation=1
InputProcessing=2
KeyEffects=0,0,0,0
KeyNextPreset=0,0,0,0
KeyOverlay=36,0,0,0
KeyPerformanceMode=0,0,0,0
KeyPreviousPreset=0,0,0,0
KeyReload=0,0,0,0

[INSTALL]
BasePath=..

[RenoDX.DLSS5]
NeuralUplift=1
NRAutoMask=0
NRColorStrength=1
NREnableUpscaling=0
NRIntensity=2
NRLocalStructure=1.01
NRLocalTone=1
NRPreset=0
NRSkinStructure=-1
NRStyle=0
NRTransferStrength=1
NRUICorrection=0
